steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'gcr.io/medicineAPI/medicineAPI:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/medicineAPI/medicineAPI:$SHORT_SHA', '.']
